name: $(Build.BuildId) -

trigger:
  batch: true
  branches:
    include:
      - master
      - refs/tags/*

jobs:
  - template: .ci/build-platform.yml
  - job: Release
    displayName: Publish release
    condition: startsWith(variables['build.sourceBranch'], 'refs/tags/')
    dependsOn: macOS
      #- Linux
      #- Windows
    pool:
      vmImage: macOS-latest
      demands: node.js
    steps:
      - template: .ci/cross-release.yml
      - task: Npm@1
        inputs:
          command: publish
          workingDir: "_release"
          publishEndpoint: NPM

